### PR TITLE
solve windows paths with spaces issue by switching to execFile?

### LINKED ISSUE #16: Codegen not working with space in directory name
If your directory address contains one or more folder names containing a space, `npm run codegen` command is not working properly.

```
PS C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server-master> npm run codegen    
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> codegen
> node generate-types.js
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server-master\node_modules\.bin\proto-loader-gen-types -I C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server-master\src\proto -O C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server-master\generated --oneofs --grpcLib=@grpc/grpc-js C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server-master\src\proto\dcs\dcs.proto
'C:\Users\benmi\Saved' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server-master\\node_modules\\.bin\\proto-loader-gen-types -I C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server-master\\src\\proto -O C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server-master\\generated --oneofs --grpcLib=@grpc/grpc-js C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server-master\\src\\proto\\dcs\\dcs.proto',
  stdout: '',
  stderr: "'C:\\Users\\benmi\\Saved' n'est pas reconnu en tant que commande interne\r\n" +
    'ou externe, un programme ex�cutable ou un fichier de commandes.\r\n'
}
```

### PR DESCRIPTION
**Pull request by bitbubbler**
attempt to solve #16

### CODE REVIEW

**Comment by bitbubbler** [comment]
@SerpentSouris26 can you try this branch?

**Comment by bitbubbler** [comment]
> @SerpentSouris26 can you try this branch?

nevermind, it's failing ci. I'll have another look at the ci failure this evening

**Comment by bitbubbler** [comment]
Ok. @SerpentSouris26 can you try this branch now? Ci is passing for windows

File: generate-types.js [hunk 1]
```diff
@@ -15,10 +15,14 @@ async function main() {
     const protoDir = resolve('src', 'proto')
     const dcsProtoFile = resolve(protoDir, 'dcs', 'dcs.proto')
 
-    const generateTypes = `${bin} -I ${protoDir} -O ${generatedDir} --oneofs --grpcLib=@grpc/grpc-js ${dcsProtoFile}`
+    const args = ['-I', protoDir, '-O', generatedDir, '--oneofs', '--grpcLib=@grpc/grpc-js', dcsProtoFile]
 
-    exec(generateTypes)
+    await execFile(bin, args, { shell: true }) // shell:true makes this work on windows
```
Comment (bitbubbler) [inline generate-types.js:20]: passing array args allows here is the fix i think. allowing node to handle spaces and encode properly. instead of us having to re-write the args encoding logic

**Comment by bitbubbler** [comment]
this seems to be working on a test windows box i cobbled together, going to merge

**Comment by SerpentSouris26** [comment]
I did a trial and modifications done in `generate-type.js` did not solve the issue. Still have : 

```
PS C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server> npm run codegen
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> codegen
> node generate-types.js

failed Error: Command failed: C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server\node_modules\.bin\proto-loader-gen-types -I C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server\src\proto -O C:\Usenother-dcs-server\src\proto -O C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server\generated --oneofs --grpcLib=@grpc/grpc-js C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-arotonother-dcs-server\src\proto\dcs\dcs.proto
'C:\Users\benmi\Saved' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,                                                                                                                                                                                     s-server\\src\\proto -O C:\\Users\\be
  cmd: 'C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server\\node_modules\\.bin\\proto-loader-gen-types -I C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs\\dcs.proto',s-server\\src\\proto -O C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server\\generated --oneofs --grpcLib=@grpc/grpc-js C:\\Users\\benmi\\Saved Games\\DCS-gRPC workspaces\\yet-another-dcs-server\\src\\proto\\dcs\\dcs.proto',
  stdout: '',
  stderr: "'C:\\Users\\benmi\\Saved' n'est pas reconnu en tant que commande interne\r\n" +
    'ou externe, un programme ex�cutable ou un fichier de commandes.\r\n'
}
PS C:\Users\benmi\Saved Games\DCS-gRPC workspaces\yet-another-dcs-server>
```
